# Generated by Django 3.2.20 on 2024-05-29 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_remove_post_num_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num_comments',
            field=models.ManyToManyField(blank=True, related_name='num_of_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
