# Generated by Django 3.2.20 on 2024-05-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_num_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='num_comments',
            new_name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented', to='blog.post'),
        ),
    ]
